credentials:
  usernames:
    fernandascovino:
      email: fernandascovino.smtr@gmail.com
      name: Fernanda
      password:
      $2b$12$Pur5PbWE7PDUOY1iJxc4vuXvO/FgETsRwMhJfvps0yQauSzCGbkP6 # hash: abc
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - fscovinom@gmail.com