# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs-validator
  template:
    metadata:
      labels:
        app: gtfs-validator
    spec:
      containers:
      - name: gtfs-validator
        image: gcr.io/$PROJECT_ID/$IMAGE_GTFS_VALIDATOR:$GITHUB_SHA
        env:
          - name: VAULT_URL
            valueFrom:
              secretKeyRef:
                name: envs
                key: VAULT_URL
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: envs
                key: VAULT_TOKEN
      restartPolicy: Always
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gtfs-validator
  name: gtfs-validator
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: gtfs-validator
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gtfs-validator-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "200m"
spec:
  tls:
    - hosts:
        - gtfs-validator.mobilidade.rio
      secretName: gtfs-validator-tls
  rules:
    - host: gtfs-validator.mobilidade.rio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gtfs-validator
                port:
                  number: 80
---
# Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: borismarinho.smtr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
